"""empty message

Revision ID: 956e908cf3ec
Revises: f543bd56880a
Create Date: 2025-05-22 21:04:34.172030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '956e908cf3ec'
down_revision = 'f543bd56880a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index('idx_fulltext_combined', ['title', 'author', 'description'], unique=False, mysql_prefix='FULLTEXT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index('idx_fulltext_combined', mysql_prefix='FULLTEXT')

    # ### end Alembic commands ###
