"""empty message

Revision ID: e92b196b7a88
Revises: 45231d7f1f1b
Create Date: 2025-05-21 20:15:46.135157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e92b196b7a88'
down_revision = '45231d7f1f1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chosen', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_cart', schema=None) as batch_op:
        batch_op.drop_column('chosen')

    # ### end Alembic commands ###
