"""empty message

Revision ID: f543bd56880a
Revises: 25c3f70e5668
Create Date: 2025-05-22 20:54:34.272258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f543bd56880a'
down_revision = '25c3f70e5668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index('idx_book_author_fulltext', ['author'], unique=False, mysql_prefix='FULLTEXT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index('idx_book_author_fulltext', mysql_prefix='FULLTEXT')

    # ### end Alembic commands ###
